baseURL = 'https://1blckhrt.github.io/knowledge-base'
languageCode = 'en-us'
title = "blckhrt's knowledge base"
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Welcome!", Content = "This site serves as a collection of knowledge and thoughts." }

  # Disable showing posts on the home page
  disableSpecial1stPost = true
  hideSummary = true

[menu]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
  name = "Music"
  url = "/posts/music/"
  parent = "Posts"
  weight = 2

[[menu.main]]
  name = "Programming"
  url = "/posts/programming/"
  parent = "Posts"
  weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  tag = "tags"
